name: my-workflow

env:
  CYPRESS_CACHE_FOLDER: cache/Cypress
on:
  pull_request:
    branches:
      - test-workflow
      - master
jobs:
  # checks the dependencies can be installed
  install:
    runs-on: ubuntu-20.04
    steps:
      # checkout the source code
      - uses: actions/checkout@v2
      # setup node
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      # cache the node_modules
      - uses: actions/cache@v2
        id: node_modules-cache
        with:
          path: node_modules
          key: ${ runner.os }-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      # install the dependencies
      - name: Install dependencies
        if: steps.node_modules-cache.outputs.cache-hit != 'true'
        run: yarn install

  test:
    needs: install
    runs-on: ubuntu-20.04
    steps:
      # checkout the source code
      - uses: actions/checkout@v2
      # setup node
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      # cache the node_modules
      - uses: actions/cache@v2
        id: node_modules-cache
        with:
          path: node_modules
          key: ${ runner.os }-node_modules-${{ hashFiles('yarn.lock') }}
      # run the app-pro cypress tests
      - name: run tests
        uses: cypress-io/github-action@v2
