name: my-workflow

on:
  pull_request:
    branches:
      - test-workflow
      - master
jobs:
  # checks the dependencies can be installed
  install:
    runs-on: ubuntu-20.04
    steps:
      # checkout the source code
      - uses: actions/checkout@v2
      # setup node
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      # cache the node_modules
      - uses: actions/cache@v2
        id: node_modules-cache
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${ runner.os }-node_modules-${{ hashFiles('yarn.lock') }}
      # install the dependencies
      - name: Install dependencies
        run: yarn install

  test-package-1:
    needs: install
    runs-on: ubuntu-20.04
    steps:
      # checkout the source code
      - uses: actions/checkout@v2
      # setup node
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      # cache the node_modules
      - uses: actions/cache@v2
        id: node_modules-cache
        with:
          path: node_modules
          key: ${ runner.os }-node_modules-${{ hashFiles('yarn.lock') }}
      # run the app-pro cypress tests
      - name: run tests
        uses: cypress-io/github-action@v2
        with:
          project: ./packages/package-1

  test-package-2:
    needs: install
    runs-on: ubuntu-20.04
    steps:
      # checkout the source code
      - uses: actions/checkout@v2
      # setup node
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      # cache the node_modules
      - uses: actions/cache@v2
        id: node_modules-cache
        with:
          path: node_modules
          key: ${ runner.os }-node_modules-${{ hashFiles('yarn.lock') }}
      # run the app-pro cypress tests
      - name: run tests
        uses: cypress-io/github-action@v2
        with:
          project: ./packages/package-2
