name: my-workflow

on:
  pull_request:
    branches:
      - test-workflow
      - master
  push:
    branches:
      - test-workflow
      - setup-push
jobs:
  prepare:
    runs-on: ubuntu-20.04
    steps:
      - name: Prepare Outputs
        id: prepare-step
        # Sets this step's outputs, that later on will be exported as the job's outputs
        run: |
          echo ${{ github.ref }}
          echo ${GITHUB_REF##*/}
          echo "::set-output name=key1::${{ github.base_ref }}";
          echo "::set-output name=key2::${GITHUB_REF##*/}";
          echo "::set-output name=key3::TEST";
    outputs:
      key1: ${{ steps.prepare-step.outputs.key1 }}
      key2: ${{ steps.prepare-step.outputs.key2 }}
      key3: ${{ steps.prepare-step.outputs.key3 }}
  test:
    needs: prepare
    runs-on: ubuntu-20.04
    env:
      WAW: ${{ needs.prepare.outputs.key1 }}
    steps:
      - name: setup env
        run: |
          echo "PRETEST=ITWORKS" >> "$GITHUB_ENV"
          echo "TEST=${{ needs.prepare.outputs.key1 }}" >> "$GITHUB_ENV"
          export TEST2=${{ needs.prepare.outputs.key1 }}
      - name: Print output
        run: |
          echo "Ready"
          echo ${{ env.PRETEST }}
          echo ${{ env.TEST }}
          echo ${{ env.TEST2 }}
          echo ${{ env.WAW }}
          if [[ ${{ env.PRETEST }} == "test-workflow" ]]; then
            echo "YES"
          else
            echo "NO"
          fi
          echo ${{ needs.prepare.outputs.key1 }}
          echo ${{ needs.prepare.outputs.key2 }}
          echo ${{ needs.prepare.outputs.key3 }}
          echo "Done"
      - name: Test Application
        run: echo ${{ secrets[format('{0}_A', 'MASTER')] }}
      - name: Test Application 2
        run: echo ${{ secrets[format('{0}_A', github.base_ref)] }}
      - name: Test Application 3
        run: echo ${{ secrets[format('{0}_A', needs.prepare.outputs.key1)] }}
      - name: Test Application 4
        run: echo ${{ secrets[format('{0}_A', needs.prepare.outputs.key2)] }}
      - name: Setup env
        run: |
          echo "${{ format('{0}_A', needs.prepare.outputs.key1) }}"
          echo "TEST1=${{ secrets[format('{0}_A', 'MASTER')] }}" >> "$GITHUB_ENV"
          echo "TEST2=${{ secrets[format('{0}_A', github.base_ref)] }}" >> "$GITHUB_ENV"
          echo "TEST3=${{ secrets[format('{0}_A', needs.prepare.outputs.key1)] }}" >> "$GITHUB_ENV"
          echo "TEST4=${{ secrets[format('{0}_A', needs.prepare.outputs.key2)] }}" >> "$GITHUB_ENV"
